/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package retail_system;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.awt.image.ImageFilter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.*;

/**
 *
 * @author sshar
 */
public class admin extends javax.swing.JFrame {
Connection conn;
Statement stmt;
ResultSet rs;
PreparedStatement preparedStmt;
    /**
     * Creates new form admin
     */
    public admin() {
        initComponents();
    }
public ArrayList<Item> BindTable(){
    
int i;
        ArrayList<Item> ite=new ArrayList<Item>();
         try{
             String host= "jdbc:derby://localhost:1527/retaildetails";
             String uName="a";
             String uPass="a";
             conn=DriverManager.getConnection(host, uName, uPass);
             stmt=conn.createStatement();
             Object selectedItem = jComboBox1.getSelectedItem();
             String selectedItemStr=null;
            
if (selectedItem != null)
{
    selectedItemStr = selectedItem.toString();
    //Foo(selectedItemStr); // Some method that takes a string parameter.
}
             String use;
                 use = jTextField1.getText();
             
             String SQL;
                 SQL = "SELECT itemid,itemname,itemprice,itemunits,category,image from item where category=?";
                
             
             preparedStmt = conn.prepareStatement(SQL);
             //PreparedStatement preparedStmt = conn.prepareStatement(SQL);
             preparedStmt.setString(1,selectedItemStr);
              rs=preparedStmt.executeQuery();
              Item  p;
              while(rs.next())
              {p=new Item(rs.getInt("itemid"),rs.getString("itemname"),rs.getInt("itemprice"),rs.getInt("itemunits"),rs.getString("category"),rs.getBytes("image"));
              ite.add(p);
              
              }
              /*String[] columnName={"Item id","Item name","Item price","Image"};
              Object[][] rows=new Object[ite.size()][6];
              for(i=0;i<ite.size();i++)
              {rows[i][0]=ite.get(i).getItemid();
              rows[i][1]=ite.get(i).getItemname();
              rows[i][2]=ite.get(i).getItemprice();
             // rows[i][3]=ite.get(i).getImage();
              
             if(ite.get(i).getmyImage()!=null){
                  ImageIcon image=new ImageIcon(new ImageIcon(ite.get(i).getmyImage()).getImage().getScaledInstance(150,120,Image.SCALE_SMOOTH));
                  rows[i][3]=ite.get(i).getmyImage();
              }
              }
              TheModel model=new TheModel(rows,columnName);
              jTable1.setModel(model);
              jTable1.setRowHeight(120);
              jTable1.getColumnModel().getColumn(3).setPreferredWidth(150);
              
            // jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            //DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();
            //tm.setRowCount(0);
              */
           
         }
      
      catch(SQLException err){
            JOptionPane.showMessageDialog(this,err.getMessage());
        }
    try {
        conn.close();
    } catch (SQLException ex) {
        Logger.getLogger(displaycart.class.getName()).log(Level.SEVERE, null, ex);
    }
    return ite;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        image = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(880, 534));
        setMinimumSize(new java.awt.Dimension(880, 534));
        setPreferredSize(new java.awt.Dimension(880, 534));
        getContentPane().setLayout(null);

        jButton1.setText("Update all stock");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(640, 440, 123, 25);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jTable1.setMinimumSize(new java.awt.Dimension(100, 640));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 110, 455, 221);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mobility aid", "Hearing aid", "Writing Aid", "Braille Equipment", "Customized Clothes", "Customized Shoes" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(127, 40, 139, 22);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Choose category");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(27, 43, 95, 16);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Item id");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(518, 52, 40, 16);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Itemname");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(510, 90, 58, 16);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Price");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(518, 140, 28, 16);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Units");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(518, 191, 28, 16);

        jButton2.setText("Image");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(500, 290, 69, 25);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(576, 49, 150, 22);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(576, 90, 150, 22);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(576, 137, 150, 22);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(576, 188, 150, 22);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(576, 291, 160, 22);
        getContentPane().add(image);
        image.setBounds(576, 345, 212, 94);

        jButton3.setText("Add");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(550, 440, 55, 25);

        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(430, 440, 73, 25);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Category");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(518, 239, 51, 16);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(576, 236, 150, 22);

        jButton5.setText("Display");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(284, 39, 73, 25);

        jButton6.setText("Display details");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(740, 20, 113, 25);

        jButton8.setText("<-");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(10, 10, 70, 25);

        jButton7.setText("Clear all");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(740, 60, 113, 25);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\sshar\\Desktop\\retail_system\\src\\retail_system\\images\\be7335a43b4bfcf59988f0cb53c8597e.png")); // NOI18N
        jLabel9.setMaximumSize(new java.awt.Dimension(900, 534));
        jLabel9.setMinimumSize(new java.awt.Dimension(900, 534));
        jLabel9.setPreferredSize(new java.awt.Dimension(900, 534));
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 910, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:776270281174
        try{String host= "jdbc:derby://localhost:1527/retaildetails";
             String uName="a";
             String uPass="a";
    
        conn=DriverManager.getConnection(host, uName, uPass);
   
        stmt=conn.createStatement();
   
        
       
        //String cell=jTable1.getModel().getValueAt(row,0).toString();
        String sql="Update item set itemunits=5";
       String use;
                 use = jTextField1.getText();
            preparedStmt=conn.prepareStatement(sql);
           
            preparedStmt.execute();
            //int row=jTable1.getSelectedRow();
            //DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
            //model.removeRow(row);
            JOptionPane.showMessageDialog(null,"Updated");   
            //jTextField1.setText(id);
            //updateTable();
        
        }
            
     catch(SQLException err){
            JOptionPane.showMessageDialog(this,err.getMessage());
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       /* BufferedImage ima = null;
       JFileChooser chooser = new JFileChooser();
		chooser.setAcceptAllFileFilterUsed(false);
      //chooser.setFileFilter(new ImageFilter());
		int retVal = chooser.showOpenDialog(this);
		if (retVal == JFileChooser.APPROVE_OPTION) {
				File myFile = chooser.getSelectedFile();
				try {
					ima= ImageIO.read(myFile);
				}
				catch( IOException e ){ 
				}
*/
        
        //        }
        JFileChooser chooser=new JFileChooser();
        chooser.showOpenDialog(null);
        File file=chooser.getSelectedFile();
        String path=file.getAbsolutePath();
        Image im=Toolkit.getDefaultToolkit().createImage(path);
        im=im.getScaledInstance(image.getWidth(),image.getHeight(),Image.SCALE_SMOOTH);
       // im= im.getScaledInstance(im.getWidth(), WIDTH, WIDTH);
        ImageIcon ii=new ImageIcon(im);
        image.setIcon(ii);
        jTextField5.setText(path);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         try{String host= "jdbc:derby://localhost:1527/retaildetails";
             String uName="a";
             String uPass="a";
    
        conn=DriverManager.getConnection(host, uName, uPass);
   
        stmt=conn.createStatement();
   String s;
         String id=jTextField1.getText();
         //String name=jTextField1.getText();
         String price=jTextField3.getText();
         String units=jTextField4.getText();
         //String id=jTextField1.getText();
        int iid = Integer.parseInt(id);
         int pr = Integer.parseInt(price);
         int uni=Integer.parseInt(units);
        //String cell=jTable1.getModel().getValueAt(row,0).toString();
        String sql="Insert into item values(?,?,?,?,?,?)";
       //String use;
           s = jTextField5.getText();
        InputStream is = new FileInputStream(new File(s));
            preparedStmt=conn.prepareStatement(sql);
            preparedStmt.setInt(1,iid);
            preparedStmt.setString(2,jTextField2.getText());
             
            //preparedStmt.setString(2,name);
            preparedStmt.setInt(3,pr);
            preparedStmt.setInt(4,uni);
            preparedStmt.setBlob(5,is);
            preparedStmt.setString(6,jTextField6.getText());
           // preparedStmt=conn.prepareStatement(sql);
            preparedStmt.execute();
            //int row=jTable1.getSelectedRow();
            //DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
            //model.removeRow(row);
            JOptionPane.showMessageDialog(null,"Item added");   
            //jTextField1.setText(id);
            //updateTable();
        
        }
            
     catch(SQLException err){
            JOptionPane.showMessageDialog(this,err.getMessage());
        } catch (FileNotFoundException ex) {
        Logger.getLogger(admin.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         try{String host= "jdbc:derby://localhost:1527/retaildetails";
             String uName="a";
             String uPass="a";
    
        conn=DriverManager.getConnection(host, uName, uPass);
   
        stmt=conn.createStatement();
   
        /* String id=jTable1.getValueAt(jTable1.getSelectedRow(),0).toString();
        String name=jTable1.getValueAt(jTable1.getSelectedRow(),1).toString();
         String pr=jTable1.getValueAt(jTable1.getSelectedRow(),2).toString();
          String units=jTable1.getValueAt(jTable1.getSelectedRow(),3).toString();
           String cat=jTable1.getValueAt(jTable1.getSelectedRow(),4).toString();
           jTextField1.setText(id);
           jTextField2.setText(name);
           jTextField3.setText(pr);
           jTextField4.setText(units);
           jTextField6.setText(cat);*/
           String id=jTextField1.getText();
           String name=jTextField2.getText();
           String pr=jTextField3.getText();
           String units=jTextField4.getText();
           String cat=jTextField6.getText();
           
           int iid = Integer.parseInt(id);
         int price = Integer.parseInt(pr);
       int uni=Integer.parseInt(units);
        //String cell=jTable1.getModel().getValueAt(row,0).toString();
        String sql="Update item set itemid=?,itemname=?,itemprice=?,itemunits=?,category=? where itemid=?";
       //String use;
                 //use = jTextField1.getText();
            preparedStmt=conn.prepareStatement(sql);
            preparedStmt.setInt(1,iid);
            preparedStmt.setString(2,name);
             
            //preparedStmt.setString(2,name);
            preparedStmt.setInt(3,price);
            preparedStmt.setInt(4,uni);
            preparedStmt.setString(5,cat);
             preparedStmt.setInt(6,iid);
           // preparedStmt=conn.prepareStatement(sql);
            preparedStmt.execute();
            //int row=jTable1.getSelectedRow();
            //DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
            //model.removeRow(row);
            JOptionPane.showMessageDialog(null,"Item updated");   
            //jTextField1.setText(id);
            //updateTable();
        
        }
            
     catch(SQLException err){
            JOptionPane.showMessageDialog(this,err.getMessage());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         ArrayList<Item> ite=BindTable();
              String[] columnName={"Item id","Item name","Item price","Units","Category","Image"};
              Object[][] rows=new Object[ite.size()][6];
              int i;
              for(i=0;i<ite.size();i++)
              {rows[i][0]=ite.get(i).getItemid();
              rows[i][1]=ite.get(i).getItemname();
              rows[i][2]=ite.get(i).getItemprice();
              rows[i][3]=ite.get(i).getItemunits();
              rows[i][4]=ite.get(i).getCategory();
             // rows[i][3]=ite.get(i).getImage();
              
             if(ite.get(i).getmyImage()!=null){
                 ImageIcon ima=new ImageIcon(new ImageIcon(ite.get(i).getmyImage()).getImage().getScaledInstance(150,120,Image.SCALE_SMOOTH));
                  //ImageIcon image=new ImageIcon(ite.get(i).getmyImage());
                   //rows[i][3]=ite.get(i).getmyImage();
                  
                 rows[i][5]=ima;
              }
              }
              TheModel model=new TheModel(rows,columnName);
              jTable1.setModel(model);
              jTable1.setRowHeight(120);
              //jTable1.getColumnModel().getColumn(3).setPreferredWidth(150);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try{String host= "jdbc:derby://localhost:1527/retaildetails";
             String uName="a";
             String uPass="a";
    
        conn=DriverManager.getConnection(host, uName, uPass);
   
        stmt=conn.createStatement();
   
         String id=jTable1.getValueAt(jTable1.getSelectedRow(),0).toString();
        String name=jTable1.getValueAt(jTable1.getSelectedRow(),1).toString();
         String pr=jTable1.getValueAt(jTable1.getSelectedRow(),2).toString();
          String units=jTable1.getValueAt(jTable1.getSelectedRow(),3).toString();
           String cat=jTable1.getValueAt(jTable1.getSelectedRow(),4).toString();
           jTextField1.setText(id);
           jTextField2.setText(name);
           jTextField3.setText(pr);
           jTextField4.setText(units);
           jTextField6.setText(cat);
           image.setIcon(null);
           jTextField5.setText(null);
             }
            
     catch(SQLException err){
            JOptionPane.showMessageDialog(this,err.getMessage());
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        image.setIcon(null);
           jTextField5.setText(null);
            jTextField1.setText(null);
             jTextField2.setText(null);
              jTextField3.setText(null);
               jTextField4.setText(null);
                jTextField5.setText(null);
                 jTextField6.setText(null);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        // String uname=jTextField1.getText();
        start s=new start();
        s.setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel image;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
