/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package retail_system;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URISyntaxException;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
/**
 *
 * @author sshar
 */
public class confirm extends javax.swing.JFrame {
Connection conn;
Statement stmt;
ResultSet rs;
PreparedStatement preparedStmt;
    /**
    /**
     * Creates new form confirm
     */
    public confirm() {
        initComponents();
    }
public confirm(String u) {
        initComponents();
        user.setText(u);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        user = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(506, 400));
        getContentPane().setLayout(null);

        jButton1.setText("Display bill");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(110, 330, 93, 25);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(43, 51, 375, 159);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Value of items");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(311, 228, 82, 16);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(417, 228, 60, 22);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Shipping charges");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(301, 260, 98, 16);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(417, 257, 60, 22);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Total");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(346, 289, 29, 16);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(417, 286, 60, 22);

        jButton2.setText("Place order");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(250, 330, 97, 25);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Welcome");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(365, 16, 53, 16);

        jButton5.setText("<-");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(10, 10, 50, 25);

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(190, 10, 69, 25);

        jButton4.setText("Display items");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(70, 10, 107, 25);

        jButton6.setText("jButton6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(390, 330, 79, 25);
        getContentPane().add(user);
        user.setBounds(425, 13, 52, 22);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\sshar\\Desktop\\retail_system\\src\\retail_system\\images\\be7335a43b4bfcf59988f0cb53c8597e.png")); // NOI18N
        jLabel5.setMaximumSize(new java.awt.Dimension(506, 400));
        jLabel5.setMinimumSize(new java.awt.Dimension(506, 400));
        jLabel5.setPreferredSize(new java.awt.Dimension(506, 400));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 510, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         try{
             String host= "jdbc:derby://localhost:1527/retaildetails";
             String uName="a";
             String uPass="a";
             conn=DriverManager.getConnection(host, uName, uPass);
             stmt=conn.createStatement();
             String use;
                 use = user.getText();
             String SQL;
                 SQL = "SELECT itemidd,price,name from cart where usern=?";
                 //ps.setString(1,user);
             
             preparedStmt = conn.prepareStatement(SQL);
             //PreparedStatement preparedStmt = conn.prepareStatement(SQL);
             preparedStmt.setString(1,use);
              rs=preparedStmt.executeQuery();
              //jTable1.getColumnModel().getColumn(3).setPreferredWidth(300);
              jTable2.setModel(DbUtils.resultSetToTableModel(rs));
            //DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();
            //tm.setRowCount(0);
              int sum=0;
              for(int i=0;i<jTable2.getRowCount();i++)
              {sum=sum+Integer.parseInt(jTable2.getValueAt(i,1).toString());
              }
              jTextField1.setText(Integer.toString(sum));
              int ship=0;
              if(sum<500)
                  ship=100;
           
              jTextField2.setText(Integer.toString(ship));
              int tot=sum+ship;
              jTextField3.setText(Integer.toString(tot));
              //conn.close();
              }
           
           
         
      
      catch(SQLException err){
            JOptionPane.showMessageDialog(this,err.getMessage());
        }
    try {
        conn.close();
    } catch (SQLException ex) {
        Logger.getLogger(displaycart.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          try{
             String host= "jdbc:derby://localhost:1527/retaildetails";
             String uName="a";
             String uPass="a";
             conn=DriverManager.getConnection(host, uName, uPass);
             stmt=conn.createStatement();
             String use;
                 use = user.getText();
             String SQL;
             for(int i=0;i<jTable2.getRowCount();i++)
             {
                 SQL = "UPDATE item set itemunits=itemunits-1 where itemid=?";
                 //ps.setString(1,user);
             
             preparedStmt = conn.prepareStatement(SQL);
             //PreparedStatement preparedStmt = conn.prepareStatement(SQL);
            // preparedStmt.setInt(1,1);
             preparedStmt.setInt(1,Integer.parseInt(jTable2.getValueAt(i,0).toString()));
              preparedStmt.executeUpdate();
             }
             String id,name,pr;
             int iid,price;
             String sql;
             for(int i=0;i<jTable2.getRowCount();i++)
             { id=jTable2.getModel().getValueAt(i,0).toString();
               name=jTable2.getModel().getValueAt(i,2).toString();
                pr=jTable2.getModel().getValueAt(i,1).toString();
                iid = Integer.parseInt(id);
               price = Integer.parseInt(pr);
                sql="Insert into history values(?,?,?,?,?)";
       //String use;
                 //use = jTextField1.getText();
                //LocalDate datee = LocalDate.now();
               // java.sql.Date sqlDate = new java.sql.Date(0L);
                java.util.Date utilDate = new java.util.Date();
                java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
                //Date myDate = datee.parse(dateee);
            preparedStmt=conn.prepareStatement(sql);
            preparedStmt.setString(4,use);
            preparedStmt.setInt(1,iid);
             
            //preparedStmt.setString(2,name);
            preparedStmt.setInt(3,price);
            preparedStmt.setString(2,name);
            preparedStmt.setDate(5,sqlDate);
            
           // preparedStmt.setString(4,"Pending");
           // preparedStmt=conn.prepareStatement(sql);
            preparedStmt.execute();
          }
             sql="DELETE FROM cart where usern=?";
       
            preparedStmt=conn.prepareStatement(sql);
            //preparedStmt.setInt(1,ii);
            preparedStmt.setString(1,use);
           // preparedStmt=conn.prepareStatement(sql);
            preparedStmt.execute();
              //jTable1.getColumnModel().getColumn(3).setPreferredWidth(300);
             // jTable2.setModel(DbUtils.resultSetToTableModel(rs));
            //DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();
            //tm.setRowCount(0);
             /* int sum=0;
              for(int i=0;i<jTable2.getRowCount();i++)
              {sum=sum+Integer.parseInt(jTable2.getValueAt(i,1).toString());
              }
              jTextField1.setText(Integer.toString(sum));
              int ship=0;
              if(sum<500)
                  ship=100;
           
              jTextField2.setText(Integer.toString(ship));
              int tot=sum+ship;
              jTextField3.setText(Integer.toString(tot));
              //conn.close();*/
             JOptionPane.showMessageDialog(null,"Order confirmed"); 
             this.setVisible(false);
              }
           
           
         
      
      catch(SQLException err){
            JOptionPane.showMessageDialog(this,err.getMessage());
        }
    try {
        conn.close();
    } catch (SQLException ex) {
        Logger.getLogger(displaycart.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         try{String host= "jdbc:derby://localhost:1527/retaildetails";
             String uName="a";
             String uPass="a";
    
        conn=DriverManager.getConnection(host, uName, uPass);
        
        stmt=conn.createStatement();
        String use=user.getText();
        
        String name=jTable2.getValueAt(jTable2.getSelectedRow(),2).toString();
        String id=jTable2.getValueAt(jTable2.getSelectedRow(),0).toString();
        int ii = Integer.parseInt(id);
        //String cell=jTable1.getModel().getValueAt(row,0).toString();
        String sql="DELETE FROM cart where itemidd=? and usern=?";
       
            preparedStmt=conn.prepareStatement(sql);
            preparedStmt.setInt(1,ii);
            preparedStmt.setString(2,use);
           // preparedStmt=conn.prepareStatement(sql);
            preparedStmt.execute();
            int row=jTable2.getSelectedRow();
            DefaultTableModel model=(DefaultTableModel) jTable2.getModel();
            model.removeRow(row);
            JOptionPane.showMessageDialog(null,"Deleted Successfully");   
            //jTextField1.setText(id);
            //updateTable();
        
        }
            
     catch(SQLException err){
            JOptionPane.showMessageDialog(this,err.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try{
             String host= "jdbc:derby://localhost:1527/retaildetails";
             String uName="a";
             String uPass="a";
             conn=DriverManager.getConnection(host, uName, uPass);
             stmt=conn.createStatement();
             String use;
                 use = user.getText();
             String SQL;
                 SQL = "SELECT itemidd,price,name from cart where usern=?";
                 //ps.setString(1,user);
             
             preparedStmt = conn.prepareStatement(SQL);
             //PreparedStatement preparedStmt = conn.prepareStatement(SQL);
             preparedStmt.setString(1,use);
              rs=preparedStmt.executeQuery();
              //jTable1.getColumnModel().getColumn(3).setPreferredWidth(300);
              jTable2.setModel(DbUtils.resultSetToTableModel(rs));
            //DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();
            //tm.setRowCount(0);
        }
           
           
         
      
      catch(SQLException err){
            JOptionPane.showMessageDialog(this,err.getMessage());
        }
    try {
        conn.close();
    } catch (SQLException ex) {
        Logger.getLogger(displaycart.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         String uname=jTextField1.getText();
        new mobilityaid1(uname).setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    try {
        // TODO add your handling code here:
        Desktop.getDesktop().browse(new URL("localhost:8383/RETAIL_SYSTEM/retail__system/newhtml.html").toURI());
    } catch (IOException ex) {
        Logger.getLogger(confirm.class.getName()).log(Level.SEVERE, null, ex);
    } catch (URISyntaxException ex) {
        Logger.getLogger(confirm.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(confirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(confirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(confirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(confirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new confirm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
