/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package retail_system;

import java.awt.Image;
import static java.awt.PageAttributes.MediaType.B;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javafx.scene.input.KeyCode.B;
import static javax.print.attribute.standard.MediaSizeName.B;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static javax.swing.text.html.HTML.Tag.B;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author sshar
 */
public class mobilityaid1 extends javax.swing.JFrame {
Connection conn;
Statement stmt;
ResultSet rs;
PreparedStatement preparedStmt;
    /**
     * Creates new form mobilityaid1
     */
    public mobilityaid1() {
        initComponents();
    }
public mobilityaid1(String uname)
    {initComponents();
   // ArrayList<Item> BindTable();
    //w.setText("Welcome");
     jTextField1.setText(uname);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    public ArrayList<Item> BindTable(){
    
int i;
        ArrayList<Item> ite=new ArrayList<Item>();
         try{
             String host= "jdbc:derby://localhost:1527/retaildetails";
             String uName="a";
             String uPass="a";
             conn=DriverManager.getConnection(host, uName, uPass);
             stmt=conn.createStatement();
             Object selectedItem = jComboBox1.getSelectedItem();
             String selectedItemStr=null;
            
if (selectedItem != null)
{
    selectedItemStr = selectedItem.toString();
    //Foo(selectedItemStr); // Some method that takes a string parameter.
}
             String use;
                 use = jTextField1.getText();
             
             String SQL;
                 SQL = "SELECT itemid,itemname,itemprice,image from item where category=?";
                
             
             preparedStmt = conn.prepareStatement(SQL);
             //PreparedStatement preparedStmt = conn.prepareStatement(SQL);
             preparedStmt.setString(1,selectedItemStr);
              rs=preparedStmt.executeQuery();
              Item  p;
              while(rs.next())
              {p=new Item(rs.getInt("itemid"),rs.getString("itemname"),rs.getInt("itemprice"),rs.getBytes("image"));
              ite.add(p);
              
              }
              /*String[] columnName={"Item id","Item name","Item price","Image"};
              Object[][] rows=new Object[ite.size()][6];
              for(i=0;i<ite.size();i++)
              {rows[i][0]=ite.get(i).getItemid();
              rows[i][1]=ite.get(i).getItemname();
              rows[i][2]=ite.get(i).getItemprice();
             // rows[i][3]=ite.get(i).getImage();
              
             if(ite.get(i).getmyImage()!=null){
                  ImageIcon image=new ImageIcon(new ImageIcon(ite.get(i).getmyImage()).getImage().getScaledInstance(150,120,Image.SCALE_SMOOTH));
                  rows[i][3]=ite.get(i).getmyImage();
              }
              }
              TheModel model=new TheModel(rows,columnName);
              jTable1.setModel(model);
              jTable1.setRowHeight(120);
              jTable1.getColumnModel().getColumn(3).setPreferredWidth(150);
              
            // jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            //DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();
            //tm.setRowCount(0);
              */
           
         }
      
      catch(SQLException err){
            JOptionPane.showMessageDialog(this,err.getMessage());
        }
    try {
        conn.close();
    } catch (SQLException ex) {
        Logger.getLogger(displaycart.class.getName()).log(Level.SEVERE, null, ex);
    }
    return ite;
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        RETAIL_SYSTEMPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("RETAIL_SYSTEMPU").createEntityManager();
        itemQuery = java.beans.Beans.isDesignTime() ? null : RETAIL_SYSTEMPUEntityManager.createQuery("SELECT i FROM Item i");
        itemList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : itemQuery.getResultList();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(719, 508));
        setMinimumSize(new java.awt.Dimension(719, 508));
        getContentPane().setLayout(null);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, itemList, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${itemid}"));
        columnBinding.setColumnName("Itemid");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${itemname}"));
        columnBinding.setColumnName("Itemname");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${itemprice}"));
        columnBinding.setColumnName("Itemprice");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${image}"));
        columnBinding.setColumnName("Image");
        columnBinding.setColumnClass(javax.swing.ImageIcon.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(29, 109, 647, 235);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(571, 13, 53, 25);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(629, 14, 78, 22);

        jButton1.setText("View items");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(420, 50, 95, 25);

        jButton2.setText("Add item");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(246, 400, 83, 25);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mobility aid", "Hearing aid", "Writing Aid", "Braille Equipment", "Customized Clothes", "Customized Shoes" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(240, 50, 139, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Choose category");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 50, 110, 17);

        jButton3.setText("View cart");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(381, 400, 87, 25);

        jButton4.setText("View history");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(604, 45, 103, 25);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\sshar\\Desktop\\retail_system\\src\\retail_system\\images\\be7335a43b4bfcf59988f0cb53c8597e.png")); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(719, 508));
        jLabel3.setMinimumSize(new java.awt.Dimension(719, 508));
        jLabel3.setPreferredSize(new java.awt.Dimension(719, 508));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 719, 508);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
              //mobilityaid1 m=new mobilityaid1();
              ArrayList<Item> ite=BindTable();
              String[] columnName={"Item id","Item name","Item price","Image"};
              Object[][] rows=new Object[ite.size()][6];
              int i;
              for(i=0;i<ite.size();i++)
              {rows[i][0]=ite.get(i).getItemid();
              rows[i][1]=ite.get(i).getItemname();
              rows[i][2]=ite.get(i).getItemprice();
             // rows[i][3]=ite.get(i).getImage();
              
             if(ite.get(i).getmyImage()!=null){
                 ImageIcon ima=new ImageIcon(new ImageIcon(ite.get(i).getmyImage()).getImage().getScaledInstance(150,120,Image.SCALE_SMOOTH));
                  //ImageIcon image=new ImageIcon(ite.get(i).getmyImage());
                   //rows[i][3]=ite.get(i).getmyImage();
                  
                 rows[i][3]=ima;
              }
              }
              TheModel model=new TheModel(rows,columnName);
              jTable1.setModel(model);
              jTable1.setRowHeight(120);
              jTable1.getColumnModel().getColumn(3).setPreferredWidth(150);
           
         
      
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{String host= "jdbc:derby://localhost:1527/retaildetails";
             String uName="a";
             String uPass="a";
    
        conn=DriverManager.getConnection(host, uName, uPass);
   
        stmt=conn.createStatement();
   
         String id=jTable1.getValueAt(jTable1.getSelectedRow(),0).toString();
        String name=jTable1.getValueAt(jTable1.getSelectedRow(),1).toString();
         String pr=jTable1.getValueAt(jTable1.getSelectedRow(),2).toString();
        int iid = Integer.parseInt(id);
         int price = Integer.parseInt(pr);
       
        //String cell=jTable1.getModel().getValueAt(row,0).toString();
        String sql="Insert into cart values(?,?,?,?,?)";
       String use;
                 use = jTextField1.getText();
            preparedStmt=conn.prepareStatement(sql);
            preparedStmt.setString(5,use);
            preparedStmt.setInt(1,iid);
             
            //preparedStmt.setString(2,name);
            preparedStmt.setInt(3,price);
            preparedStmt.setString(2,name);
            preparedStmt.setString(4,"Pending");
           // preparedStmt=conn.prepareStatement(sql);
            preparedStmt.execute();
            //int row=jTable1.getSelectedRow();
            //DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
            //model.removeRow(row);
            JOptionPane.showMessageDialog(null,"Item added");   
            //jTextField1.setText(id);
            //updateTable();
        
        }
            
     catch(SQLException err){
            JOptionPane.showMessageDialog(this,err.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String uname=jTextField1.getText();
        new confirm(uname).setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String uname=jTextField1.getText();
        new track(uname).setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mobilityaid1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mobilityaid1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mobilityaid1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mobilityaid1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
   
        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new mobilityaid1().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager RETAIL_SYSTEMPUEntityManager;
    private java.util.List<retail_system.Item> itemList;
    private javax.persistence.Query itemQuery;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
