/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package retail_system;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;

/**
 *
 * @author sshar
 */
public class track extends javax.swing.JFrame {
Connection conn;
Statement stmt;
ResultSet rs;
PreparedStatement preparedStmt;
    /**
     * Creates new form track
     */
    public track() {
        initComponents();
    }
    
public track(String u) {
        initComponents();
        user.setText(u);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 520));
        setMinimumSize(new java.awt.Dimension(800, 520));
        setPreferredSize(new java.awt.Dimension(800, 520));
        getContentPane().setLayout(null);

        jButton1.setText("View history");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(199, 34, 103, 25);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(44, 77, 452, 181);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(460, 30, 53, 16);
        getContentPane().add(user);
        user.setBounds(530, 30, 54, 22);

        jButton2.setText("Track");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(550, 90, 65, 25);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(520, 160, 103, 28);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(680, 160, 100, 28);

        jButton3.setText("<-");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(30, 10, 60, 25);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(520, 230, 103, 24);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(680, 230, 100, 24);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\sshar\\Desktop\\retail_system\\src\\retail_system\\images\\be7335a43b4bfcf59988f0cb53c8597e.png")); // NOI18N
        jLabel6.setMaximumSize(new java.awt.Dimension(909, 521));
        jLabel6.setMinimumSize(new java.awt.Dimension(909, 521));
        jLabel6.setPreferredSize(new java.awt.Dimension(909, 521));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 890, 521);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         try{
             String host= "jdbc:derby://localhost:1527/retaildetails";
             String uName="a";
             String uPass="a";
             conn=DriverManager.getConnection(host, uName, uPass);
             stmt=conn.createStatement();
             String use;
                 use = user.getText();
             String SQL;
                 SQL = "SELECT itemiid,iname,iprice,dateoforder from history where userna=?";
                 //ps.setString(1,user);
             
             preparedStmt = conn.prepareStatement(SQL);
             //PreparedStatement preparedStmt = conn.prepareStatement(SQL);
             preparedStmt.setString(1,use);
              rs=preparedStmt.executeQuery();
              //jTable1.getColumnModel().getColumn(3).setPreferredWidth(300);
              jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            //DefaultTableModel tm=(DefaultTableModel)jTable1.getModel();
            //tm.setRowCount(0);
        }
           
           
         
      
      catch(SQLException err){
            JOptionPane.showMessageDialog(this,err.getMessage());
        }
    try {
        conn.close();
    } catch (SQLException ex) {
        Logger.getLogger(displaycart.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         try{String host= "jdbc:derby://localhost:1527/retaildetails";
             String uName="a";
             String uPass="a";
    
        conn=DriverManager.getConnection(host, uName, uPass);
   
        stmt=conn.createStatement();
   
         Date d=(Date) jTable1.getValueAt(jTable1.getSelectedRow(),3);
      java.util.Date utilDate = new java.util.Date();
                java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
                long difference =  (sqlDate.getTime()-d.getTime())/86400000;
        int days=(int) Math.abs(difference);
        String dd="";
       Calendar c = Calendar.getInstance();
        c.setTime(d);
        c.add(Calendar.DATE, 3);
        //Date estDate=d;
        //Date estDate = (Date) c.getTime();
        String pattern = "yyyy/MM/dd";

DateFormat df = new SimpleDateFormat(pattern);
//Calendar c1 = Calendar.getInstance();
        //c1.setTime(estDate);
//Calender estDate= Calendar.getInstance();        
//jTextField1.setText(dd);
String da=Integer.toString(days);
//jTextField1.setText(da);
String est = df.format(c.getTime());
        if(days<=2){
            dd="<html> Order confirmed <br>  Order dispatched </html>";
            jLabel3.setText(dd);
        jLabel2.setText("Status");
        jLabel5.setText(est);
        jLabel4.setText("Estimated delivery date");
        }
        else if(days==3){
            dd="Out for delivery";
            jLabel3.setText(dd);
        jLabel2.setText("Status");
        jLabel5.setText(est);
        jLabel4.setText("Estimated delivery date");
        }
        else{
            dd="Delivered";
            jLabel3.setText(dd);
        jLabel2.setText("Status");}
       // String dd=parse.String(days);
        //String dd = Integer.toString(days);
       
        
        }
            
     catch(SQLException err){
            JOptionPane.showMessageDialog(this,err.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         String uname=user.getText();
        new mobilityaid1(uname).setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(track.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(track.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(track.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(track.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new track().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
